### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andrei923** [OfficialDonut/SkUniversal#5]
`add "%{_prefix}%" with priority 6 to LuckPerms prefixes of player`

```
[14:32:56 WARN]: [LuckPerms] Unable to pass event NodeAddEvent to handler us._donut_.skuniversal.luckperms.LuckPermsListener$$Lambda$154/2133821539
[14:32:56 WARN]: java.lang.reflect.UndeclaredThrowableException
[14:32:56 WARN]:        at com.sun.proxy.$Proxy26.isUser(Unknown Source)
[14:32:56 WARN]:        at us._donut_.skuniversal.luckperms.LuckPermsListener.onGroupChange(LuckPermsListener.java:37)
[14:32:56 WARN]:        at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
[14:32:56 WARN]:        at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
[14:32:56 WARN]:        at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[14:32:56 WARN]:        at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[14:32:56 WARN]:        at me.lucko.luckperms.common.event.EventFactory.post(EventFactory.java:111)
[14:32:56 WARN]:        at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:124)
[14:32:56 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)
[14:32:56 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:32:56 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:32:56 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[14:32:56 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[14:32:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:32:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:32:56 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:32:56 WARN]: Caused by: java.lang.IllegalAccessException: no private access for invokespecial: interface me.lucko.luckperms.api.event.node.NodeMutateEvent, from me.lucko.luckperms.api.event.node.NodeMutateEvent/public
[14:32:56 WARN]:        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:850)
[14:32:56 WARN]:        at java.lang.invoke.MethodHandles$Lookup.checkSpecialCaller(MethodHandles.java:1572)
[14:32:56 WARN]:        at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1231)
[14:32:56 WARN]:        at me.lucko.luckperms.common.event.gen.GeneratedEventSpec$EventInvocationHandler.invoke(GeneratedEventSpec.java:153)
[14:32:56 WARN]:        ... 16 more
```

**Comment by OfficialDonut** [comment]
This is a problem with Luckperms, I have already reported it to them
